#define _POSIX_C_SOURCE 200809L
#include <arpa/inet.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#define PORT 8090
#define MAX_PACKAGE (8 * 1024 * 1024)
#define WORK "/mnt/userdata/.beacon-ota"
#define WEB "/mnt/userdata/beacon-web"
#define WEB_OLD "/mnt/userdata/beacon-web.previous"
#define TOOLS "/mnt/userdata/beacon-tools"
#define TOOLS_OLD "/mnt/userdata/beacon-tools.previous"

typedef struct { uint32_t h[8]; uint64_t bits; unsigned char block[64]; size_t used; } sha256_ctx;
static const uint32_t K[64]={0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};
static uint32_t rr(uint32_t x,int n){return(x>>n)|(x<<(32-n));}
static void sha_block(sha256_ctx*c,const unsigned char*b){uint32_t w[64],a,d,e,f,g,h,i,t1,t2,bb,cc;for(i=0;i<16;i++)w[i]=(uint32_t)b[i*4]<<24|(uint32_t)b[i*4+1]<<16|(uint32_t)b[i*4+2]<<8|b[i*4+3];for(i=16;i<64;i++){uint32_t s0=rr(w[i-15],7)^rr(w[i-15],18)^(w[i-15]>>3),s1=rr(w[i-2],17)^rr(w[i-2],19)^(w[i-2]>>10);w[i]=w[i-16]+s0+w[i-7]+s1;}a=c->h[0];bb=c->h[1];cc=c->h[2];d=c->h[3];e=c->h[4];f=c->h[5];g=c->h[6];h=c->h[7];for(i=0;i<64;i++){uint32_t s1=rr(e,6)^rr(e,11)^rr(e,25),ch=(e&f)^(~e&g),s0=rr(a,2)^rr(a,13)^rr(a,22),maj=(a&bb)^(a&cc)^(bb&cc);t1=h+s1+ch+K[i]+w[i];t2=s0+maj;h=g;g=f;f=e;e=d+t1;d=cc;cc=bb;bb=a;a=t1+t2;}c->h[0]+=a;c->h[1]+=bb;c->h[2]+=cc;c->h[3]+=d;c->h[4]+=e;c->h[5]+=f;c->h[6]+=g;c->h[7]+=h;}
static void sha_init(sha256_ctx*c){uint32_t x[8]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};memcpy(c->h,x,32);c->bits=0;c->used=0;}
static void sha_add(sha256_ctx*c,const unsigned char*p,size_t n){c->bits+=(uint64_t)n*8;while(n){size_t z=64-c->used;if(z>n)z=n;memcpy(c->block+c->used,p,z);c->used+=z;p+=z;n-=z;if(c->used==64){sha_block(c,c->block);c->used=0;}}}
static void sha_end(sha256_ctx*c,char out[65]){uint64_t bits=c->bits;size_t i;c->block[c->used++]=0x80;if(c->used>56){while(c->used<64)c->block[c->used++]=0;sha_block(c,c->block);c->used=0;}while(c->used<56)c->block[c->used++]=0;for(i=0;i<8;i++)c->block[63-i]=(unsigned char)(bits>>(i*8));sha_block(c,c->block);for(i=0;i<8;i++)sprintf(out+i*8,"%08x",c->h[i]);out[64]=0;}

static int run4(const char*a,const char*b,const char*c,const char*d){pid_t p=fork();int s;if(p<0)return-1;if(!p){execl(a,a,b,c,d,(char*)0);_exit(127);}return waitpid(p,&s,0)<0||!WIFEXITED(s)||WEXITSTATUS(s);}
static int run5(const char*a,const char*b,const char*c,const char*d,const char*e){pid_t p=fork();int s;if(p<0)return-1;if(!p){execl(a,a,b,c,d,e,(char*)0);_exit(127);}return waitpid(p,&s,0)<0||!WIFEXITED(s)||WEXITSTATUS(s);}
static int rmrf(const char*p){return run4("/bin/rm","-rf",p,NULL);}
static int exists(const char*p){struct stat s;return stat(p,&s)==0&&S_ISREG(s.st_mode);}
static void cfg(const char*k,char*out,size_t n){char cmd[96];FILE*f;snprintf(cmd,sizeof cmd,"/bin/cfg get %s",k);out[0]=0;f=popen(cmd,"r");if(f){fgets(out,n,f);pclose(f);out[strcspn(out,"\r\n")]=0;}}
static int valid_hex(const char*s){int i;if(strlen(s)!=64)return 0;for(i=0;i<64;i++)if(!((s[i]>='0'&&s[i]<='9')||(s[i]>='a'&&s[i]<='f')))return 0;return 1;}
static int valid_ver(const char*s){size_t i,n=strlen(s);if(!n||n>24)return 0;for(i=0;i<n;i++)if(!((s[i]>='0'&&s[i]<='9')||(s[i]>='a'&&s[i]<='z')||s[i]=='.'||s[i]=='-'))return 0;return 1;}
static void reply(int fd,int code,const char*origin,const char*msg,const char*ver){char body[512],head[1024];int bl,hl;bl=snprintf(body,sizeof body,"{\"ok\":%s,\"message\":\"%s\"%s%s%s}",code<400?"true":"false",msg,ver?",\"version\":\"":"",ver?ver:"",ver?"\"":"");hl=snprintf(head,sizeof head,"HTTP/1.1 %d %s\r\nContent-Type: application/json\r\nContent-Length: %d\r\nConnection: close\r\n%s%s%s\r\n",code,code<400?"OK":"Error",bl,origin&&*origin?"Access-Control-Allow-Origin: ":"",origin&&*origin?origin:"",origin&&*origin?"\r\nVary: Origin\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS\r\nAccess-Control-Allow-Headers: Content-Type, X-Beacon-SHA256, X-Beacon-Version\r\n":"");write(fd,head,hl);if(code!=204)write(fd,body,bl);}
static int header(const char*request,const char*name,char*out,size_t cap){const char*p=request,*e;size_t n=strlen(name),z;out[0]=0;while((p=strstr(p,"\r\n"))){p+=2;if(!strncasecmp(p,name,n)&&p[n]==':'){p+=n+1;while(*p==' ')p++;e=strstr(p,"\r\n");if(!e)return 0;z=(size_t)(e-p);if(z>=cap)z=cap-1;memcpy(out,p,z);out[z]=0;return 1;}}return 0;}
static int safe_zip(const char*p){FILE*f;char line[512],cmd[320];int bad=0;snprintf(cmd,sizeof cmd,"/usr/bin/unzip -l %s",p);f=popen(cmd,"r");if(!f)return 0;while(fgets(line,sizeof line,f))if(strstr(line,"../")||strstr(line,"..\\")||strstr(line,"   /")){bad=1;break;}if(pclose(f)!=0)bad=1;return!bad;}
static int manifest_ok(const char*ver){char buf[512],needle[96];FILE*f=fopen(WORK "/stage/web/beacon-version.json","r");size_t n;if(!f)return 0;n=fread(buf,1,sizeof(buf)-1,f);buf[n]=0;fclose(f);snprintf(needle,sizeof needle,"\"version\":\"%s\"",ver);return strstr(buf,needle)!=NULL;}
static int install_zip(const char*ver,char*err,size_t en){rmrf(WORK "/stage");mkdir(WORK "/stage",0755);if(run5("/usr/bin/unzip","-oq",WORK "/package.zip","-d",WORK "/stage")){snprintf(err,en,"OTA extraction failed");return-1;}if(!exists(WORK "/stage/web/index.html")||!exists(WORK "/stage/web/mobile.html")||!exists(WORK "/stage/router-tools/beacon-agent.sh")||!exists(WORK "/stage/router-tools/beacon-ota")||!manifest_ok(ver)){snprintf(err,en,"OTA package contents or version are invalid");return-1;}if(exists(TOOLS "/led.conf"))run4("/bin/cp",TOOLS "/led.conf",WORK "/stage/router-tools/led.conf",NULL);rmrf(WEB_OLD);rmrf(TOOLS_OLD);if(rename(WEB,WEB_OLD)){snprintf(err,en,"Could not preserve current UI");return-1;}if(rename(WORK "/stage/web",WEB)){rename(WEB_OLD,WEB);snprintf(err,en,"Could not activate new UI");return-1;}if(rename(TOOLS,TOOLS_OLD)){rmrf(WEB);rename(WEB_OLD,WEB);snprintf(err,en,"Could not preserve current tools");return-1;}if(rename(WORK "/stage/router-tools",TOOLS)){rename(TOOLS_OLD,TOOLS);rmrf(WEB);rename(WEB_OLD,WEB);snprintf(err,en,"Could not activate new tools");return-1;}chmod(TOOLS "/beacon-agent.sh",0755);chmod(TOOLS "/beacon-ota",0755);symlink("/tmp/beacon-system.json",WEB "/beacon-system.json");return 0;}
static void serve(int fd){char req[32768],method[12],path[128],lan[64],allowed[96],login[32],origin[128],length_s[32],expected[80],version[32],err[160],digest[65];char*end;size_t got=0,headn,have;long length,remain;int out;sha256_ctx sha;while(got<sizeof(req)-1){ssize_t n=read(fd,req+got,sizeof(req)-1-got);if(n<=0)return;got+=n;req[got]=0;if((end=strstr(req,"\r\n\r\n")))break;}if(!end)return;sscanf(req,"%11s %127s",method,path);header(req,"Origin",origin,sizeof origin);cfg("lan_ipaddr",lan,sizeof lan);snprintf(allowed,sizeof allowed,"http://%s",lan);if(*origin&&strcmp(origin,allowed)){reply(fd,403,origin,"Request origin rejected",NULL);return;}if(!strcmp(method,"OPTIONS")){reply(fd,204,origin,"",NULL);return;}if(!strcmp(method,"GET")&&!strcmp(path,"/health")){reply(fd,200,origin,"Beacon OTA helper ready",NULL);return;}if(strcmp(method,"POST")||strcmp(path,"/install")){reply(fd,404,origin,"Endpoint not found",NULL);return;}if(!*origin){reply(fd,403,origin,"Browser origin is required",NULL);return;}cfg("loginfo",login,sizeof login);if(strcmp(login,"ok")){reply(fd,401,origin,"Sign in to the router as administrator first",NULL);return;}header(req,"Content-Length",length_s,sizeof length_s);length=strtol(length_s,NULL,10);header(req,"X-Beacon-SHA256",expected,sizeof expected);if(!strncasecmp(expected,"sha256:",7))memmove(expected,expected+7,strlen(expected+7)+1);header(req,"X-Beacon-Version",version,sizeof version);if(length<1||length>MAX_PACKAGE||!valid_hex(expected)||!valid_ver(version)){reply(fd,400,origin,"Invalid OTA package or release metadata",NULL);return;}rmrf(WORK);mkdir(WORK,0755);out=open(WORK "/package.zip",O_CREAT|O_TRUNC|O_WRONLY,0600);if(out<0){reply(fd,500,origin,"Could not stage OTA package",NULL);return;}sha_init(&sha);headn=(size_t)((end+4)-req);have=got-headn;if(have>(size_t)length)have=(size_t)length;if(have){write(out,req+headn,have);sha_add(&sha,(unsigned char*)req+headn,have);}remain=length-(long)have;while(remain>0){unsigned char b[16384];ssize_t n=read(fd,b,remain<(long)sizeof b?(size_t)remain:sizeof b);if(n<=0)break;if(write(out,b,n)!=n)break;sha_add(&sha,b,n);remain-=n;}fsync(out);close(out);sha_end(&sha,digest);if(remain||strcmp(digest,expected)){rmrf(WORK);reply(fd,400,origin,"OTA upload or checksum verification failed",NULL);return;}if(!safe_zip(WORK "/package.zip")){rmrf(WORK);reply(fd,400,origin,"OTA package is not a safe ZIP",NULL);return;}if(install_zip(version,err,sizeof err)){rmrf(WORK);reply(fd,500,origin,err,NULL);return;}rmrf(WORK);reply(fd,200,origin,"Beacon update installed",version);}
int main(void){int s,c,yes=1;struct sockaddr_in a;signal(SIGPIPE,SIG_IGN);s=socket(AF_INET,SOCK_STREAM,0);if(s<0)return 1;setsockopt(s,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof yes);memset(&a,0,sizeof a);a.sin_family=AF_INET;a.sin_port=htons(PORT);a.sin_addr.s_addr=htonl(INADDR_ANY);if(bind(s,(struct sockaddr*)&a,sizeof a)||listen(s,2))return 2;for(;;){c=accept(s,NULL,NULL);if(c>=0){serve(c);close(c);}}}
