import { createRouterClient } from "../router-client";
import { getRouterSession } from "../session-store";

export const dynamic = "force-dynamic";
const commands=["tc_traffic_enable","upload_width_manual","download_width_manual",...Array.from({length:10},(_,index)=>`userspeedlimit_${index}`)].join(",");
function validIp(input:string){const parts=input.split(".");return parts.length===4&&parts.every((part)=>/^\d{1,3}$/.test(part)&&Number(part)<=255);}
function parse(data:Record<string,unknown>){const rules=[];for(let index=0;index<10;index++){const raw=String(data[`userspeedlimit_${index}`]||"");if(!raw)continue;const fields=raw.split(",");rules.push({index,ipStart:fields[0]||"",ipEnd:fields[1]||"",portStart:fields[2]||"1",portEnd:fields[3]||"65535",protocol:fields[4]==="0"?"ALL":fields[4]==="1"?"TCP":"UDP",priority:fields[5]||"1",uploadMin:Number(fields[6])||0,uploadMax:Number(fields[7])||0,downloadMin:Number(fields[8])||0,downloadMax:Number(fields[9])||0,enabled:fields[10]!=="0"});}return {ok:true,enabled:String(data.tc_traffic_enable||"")==="1",uploadTotal:Number(data.upload_width_manual)||0,downloadTotal:Number(data.download_width_manual)||0,rules};}
export async function GET(request:Request){const session=getRouterSession(request);if(!session)return Response.json({ok:false,error:"Router login required"},{status:401});try{const router=createRouterClient(session);await router.ensureAuth();return Response.json(parse(await router.get(commands)),{headers:{"Cache-Control":"no-store"}});}catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:"Traffic-control request failed"},{status:502});}}
export async function POST(request:Request){const session=getRouterSession(request);if(!session)return Response.json({ok:false,error:"Router login required"},{status:401});try{const input=await request.json() as {action?:string;payload?:Record<string,unknown>;confirmed?:boolean};if(input.confirmed!==true)throw new Error("Confirmation is required");const payload=input.payload||{};const router=createRouterClient(session);await router.ensureAuth();if(input.action==="traffic_delete"){const index=Math.trunc(Number(payload.index));if(index<0||index>9)throw new Error("Invalid speed-limit rule");await router.post({goformId:"TRAFFIC_CONTROL_DEL",delete_id:`${index};`});return Response.json({ok:true,action:input.action});}if(input.action==="traffic_toggle"){await router.post({goformId:"TRAFFIC_CONTROL_SWITCH_SET",tc_traffic_enable:payload.enabled===true?"1":"0",upload_width_manual:String(Math.max(100,Number(payload.uploadTotal)||1000000)),download_width_manual:String(Math.max(100,Number(payload.downloadTotal)||1000000))});return Response.json({ok:true,action:input.action});}if(input.action!=="traffic_upsert")throw new Error("Unsupported traffic-control action");const ip=String(payload.ip||"").trim(),upload=Math.trunc(Number(payload.uploadKbps)),download=Math.trunc(Number(payload.downloadKbps));if(!validIp(ip))throw new Error("Enter a valid device IPv4 address");if(upload<10||download<10||upload>1000000||download>1000000)throw new Error("Speed limits must be between 10 and 1,000,000 Kbps");const current=parse(await router.get(commands));await router.post({goformId:"TRAFFIC_CONTROL_SWITCH_SET",tc_traffic_enable:"1",upload_width_manual:String(Math.max(100,current.uploadTotal,upload)),download_width_manual:String(Math.max(100,current.downloadTotal,download))});await router.post({goformId:"TRAFFIC_CONTROL_ADD",enable:"1",ip_start:ip,ip_end:ip,portStart:"1",portEnd:"65535",protocol:"ALL",priority:"1",upload_min:"10",upload_max:String(upload),download_min:"10",download_max:String(download)});return Response.json({ok:true,action:input.action});}catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:"Traffic-control change failed"},{status:400});}}
