import { createRouterClient } from "../router-client";
import { getRouterSession } from "../session-store";

export const dynamic = "force-dynamic";
const masks:Record<string,string>={"3":"0x000000004","5":"0x000000010","38":"0x2000000000","41":"0x10000000000"};
function selectedBands(maskValue:unknown){const parts=String(maskValue||"").split(";").filter(Boolean);const combined=parts.length>1?parts.reduce((sum,part)=>sum+(Number.parseInt(part,16)||0),0):(Number.parseInt(parts[0]||"0",16)||0);return Object.entries(masks).filter(([,mask])=>Math.floor(combined/Number.parseInt(mask,16))%2===1).map(([band])=>band);}

export async function GET(request:Request){const session=getRouterSession(request);if(!session)return Response.json({ok:false,error:"Router login required"},{status:401});try{const router=createRouterClient(session);await router.ensureAuth();const data=await router.get("lte_band_lock,wcdma_band_lock,net_select,lte_pci,cell_id,wan_active_band,wan_active_channel,lte_rsrp,lte_rsrq,lte_snr");const locked=String(data.lte_band_lock||"");return Response.json({ok:true,networkSelection:String(data.net_select||""),lteBandLock:locked,wcdmaBandLock:String(data.wcdma_band_lock||""),selectedBands:selectedBands(locked),availableBands:Object.keys(masks),current:{band:String(data.wan_active_band||""),channel:String(data.wan_active_channel||""),pci:String(data.lte_pci||""),cellId:String(data.cell_id||""),rsrp:Number(data.lte_rsrp)||0,rsrq:Number(data.lte_rsrq)||0,sinr:Number(data.lte_snr)||0},cellLockSupported:false,neighborScanSupported:false,cellLockReason:"The modem adapter contains neighbor-cell telemetry internally, but this MF293N firmware exposes no authenticated neighbor scan or cell-lock command. Beacon will not guess a write command."},{headers:{"Cache-Control":"no-store"}});}catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:"Radio request failed"},{status:502});}}

export async function POST(request:Request){const session=getRouterSession(request);if(!session)return Response.json({ok:false,error:"Router login required"},{status:401});try{const input=await request.json() as {action?:string;payload?:Record<string,unknown>;confirmed?:boolean};if(input.confirmed!==true)throw new Error("Confirmation is required");if(input.action!=="band_update")throw new Error("Unsupported radio action");const selected=Array.isArray(input.payload?.bands)?input.payload?.bands.map(String).filter((band)=>masks[band]):[];if(!selected.length)throw new Error("Select at least one LTE band");const router=createRouterClient(session);await router.ensureAuth();const status=await router.get("ppp_status");const connected=String(status.ppp_status)==="ppp_connected";if(connected){await router.post({goformId:"DISCONNECT_NETWORK"});await new Promise((resolve)=>setTimeout(resolve,2500));}let applied:string[]=[];try{await router.post({goformId:"SET_NETWORK_BAND_LOCK",lte_band_lock:selected.map((band)=>masks[band]).join(";")+";",wcdma_band_lock:"0x000000000",is_gw_band:"1",is_lte_band:"0"});for(let attempt=0;attempt<8;attempt++){await new Promise((resolve)=>setTimeout(resolve,500));applied=selectedBands((await router.get("lte_band_lock")).lte_band_lock);if(selected.every((band)=>applied.includes(band))&&applied.length===selected.length)break;}if(!selected.every((band)=>applied.includes(band))||applied.length!==selected.length)throw new Error(`Band lock verification failed; router reports ${applied.join(", ")||"none"}`);}finally{if(connected)await router.post({goformId:"CONNECT_NETWORK"});}return Response.json({ok:true,action:input.action,appliedBands:applied});}catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:"Band change failed"},{status:400});}}
