import { createRouterClient } from "../router-client";
import { getRouterSession } from "../session-store";

export const dynamic = "force-dynamic";

function text(value:unknown,max=512){return String(value??"").trim().slice(0,max);}
function decodeModemText(value:unknown){const raw=String(value??"");if(/^(?:[0-9a-fA-F]{4})+$/.test(raw)){let result="";for(let i=0;i<raw.length;i+=4)result+=String.fromCharCode(parseInt(raw.slice(i,i+4),16));return result;}try{return decodeURIComponent(raw);}catch{return raw;}}
function encodeUnicode(value:string){return Array.from(value).map((character)=>character.charCodeAt(0).toString(16).padStart(4,"0").toUpperCase()).join("");}
function smsTime(){const d=new Date();const two=(n:number)=>String(n).padStart(2,"0");const offset=-d.getTimezoneOffset()/60;return `${String(d.getFullYear()).slice(-2)};${two(d.getMonth()+1)};${two(d.getDate())};${two(d.getHours())};${two(d.getMinutes())};${two(d.getSeconds())};${offset>=0?"+":""}${offset}`;}
function date(value:unknown){const parts=String(value??"").split(",");if(parts.length<6)return String(value??"");return `20${parts[0]}-${parts[1]}-${parts[2]} ${parts[3]}:${parts[4]}:${parts[5]}`;}

export async function GET(request:Request){const session=getRouterSession(request);if(!session)return Response.json({ok:false,error:"Router login required"},{status:401});try{const router=createRouterClient(session);await router.ensureAuth();const [sms,capacity]=await Promise.all([router.getParams({cmd:"sms_data_total",page:"0",data_per_page:"500",mem_store:"1",tags:"10",order_by:"order by id desc"}),router.get("sms_capacity_info")]);const raw=Array.isArray(sms.messages)?sms.messages as Array<Record<string,unknown>>:[];const messages=raw.map((item)=>({id:text(item.id,32),number:text(item.number,64),content:decodeModemText(item.content),time:date(item.date),unread:String(item.tag)==="1",tag:text(item.tag,8)}));return Response.json({ok:true,messages,capacity:{total:Number(capacity.sms_nv_total)||0,received:Number(capacity.sms_nv_rev_total)||0,sent:Number(capacity.sms_nv_send_total)||0,drafts:Number(capacity.sms_nv_draftbox_total)||0}},{headers:{"Cache-Control":"no-store"}});}catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:"Communication request failed"},{status:502});}}

export async function POST(request:Request){const session=getRouterSession(request);if(!session)return Response.json({ok:false,error:"Router login required"},{status:401});try{const input=await request.json() as {action?:unknown;payload?:Record<string,unknown>;confirmed?:unknown};if(input.confirmed!==true)throw new Error("Confirmation is required");const action=text(input.action,40),payload=input.payload||{},router=createRouterClient(session);await router.ensureAuth();if(action==="sms_send"){const number=text(payload.number,32),message=text(payload.message,765);if(!/^\+?[0-9A-Za-z]{3,20}$/.test(number)||!message)throw new Error("Enter a valid recipient and message");await router.post({goformId:"SEND_SMS",Number:number,sms_time:smsTime(),MessageBody:encodeUnicode(message),ID:"-1",encode_type:"UNICODE"});}else if(action==="sms_read"){const id=text(payload.id,32);await router.post({goformId:"SET_MSG_READ",msg_id:`${id};`,tag:"0"});}else if(action==="sms_delete"){const id=text(payload.id,32);await router.post({goformId:"DELETE_SMS",msg_id:`${id};`});}else if(action==="ussd_cancel"){await router.post({goformId:"USSD_PROCESS",USSD_operator:"ussd_cancel"});return Response.json({ok:true,action});}else if(action==="ussd_send"||action==="ussd_reply"){const command=text(payload.command,182);if(!command)throw new Error("Enter a USSD code or reply");const operator=action==="ussd_reply"?"ussd_reply":"ussd_send";await router.post({goformId:"USSD_PROCESS",USSD_operator:operator,[action==="ussd_reply"?"USSD_reply_number":"USSD_send_number"]:command});for(let attempt=0;attempt<45;attempt++){await new Promise((resolve)=>setTimeout(resolve,1000));const flag=String((await router.getParams({cmd:"ussd_write_flag"})).ussd_write_flag||"");if(flag==="15")continue;if(flag==="16"){const result=await router.getParams({cmd:"ussd_data_info"});return Response.json({ok:true,action,response:{content:decodeModemText(result.ussd_data),action:String(result.ussd_action||""),dcs:String(result.ussd_dcs||"")}});}const errors:Record<string,string>={"1":"No mobile service","2":"Network ended the session","3":"USSD request timed out","4":"USSD request timed out","10":"Please retry the USSD request","41":"Operation not supported","99":"USSD is unsupported"};throw new Error(errors[flag]||"USSD request failed");}throw new Error("USSD request timed out");}else throw new Error("Unsupported communication action");return Response.json({ok:true,action});}catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:"Communication action failed"},{status:400});}}
